import { useState } from 'react';
import { FiPlus, FiEdit2, FiTrash2, FiVideo, FiArrowLeft } from 'react-icons/fi';
import { useModelStore } from '../../store/modelStore';
import { useConnectionStore } from '../../store/connectionStore';
import type { ModelConfig } from '../../types';
import { useI18n } from '../../hooks/useI18n';
import { confirmDestructive } from '../../store/confirmStore';
import { HUB_INPUT, HUB_PRIMARY, HUB_SECONDARY, HUB_CARD, HUB_FORM, HUB_LABEL, HUB_HINT, HUB_BADGE, HUB_ERROR } from '../modelHub/styles';
const empty = { id: '', name: '', connectionId: '', apiKey: '', model: 'MiniMax-Hailuo-02', endpoint: 'https://api.minimaxi.com', resolution: '768' as '480' | '720' | '768' | '1080', duration: 6 as 5 | 6 | 10 };
export function VideoModelsSection({ cardShell, embedded = false }: { cardShell: string; embedded?: boolean }) {
  const { locale } = useI18n(); const label = (zh: string, en: string) => locale === 'en' ? en : zh;
  const { models, addModel, updateModel, removeModel } = useModelStore(); const connections = useConnectionStore(s => s.connections); const videos = models.filter(m => m.isVideoGenerator && m.videoGeneratorConfig);
  const [draft, setDraft] = useState<typeof empty | null>(null); const [error, setError] = useState(''); const back = () => { setDraft(null); setError(''); };
  const save = () => {
    if (!draft) return;
    try {
      const endpoint = new URL(draft.endpoint); if (!['http:', 'https:'].includes(endpoint.protocol) || endpoint.username || endpoint.password || !draft.model.trim()) throw new Error(label('请填写有效的模型和服务地址', 'Enter a valid model and endpoint'));
      const connection = connections.find(c => c.id === draft.connectionId); if (!draft.apiKey.trim() && !connection?.apiKey) throw new Error(label('请填写视频密钥或选择已有服务连接', 'Enter a key or select a service connection'));
      const old = models.find(m => m.id === draft.id);
      const model: ModelConfig = { ...(old || {}), id: draft.id || crypto.randomUUID(), name: draft.name.trim() || draft.model, modelName: old?.modelName || draft.model, provider: old?.provider || 'custom', apiUrl: old?.apiUrl || draft.endpoint, isLocal: old?.isLocal ?? false, isChatModel: old?.isChatModel ?? false, maxTokens: old?.maxTokens || 4096, isVideoGenerator: true, connectionId: old?.connectionId, videoGeneratorConfig: { ...(old?.videoGeneratorConfig || {}), connectionId: draft.connectionId || undefined, provider: 'minimax', endpoint: draft.endpoint.trim(), apiKey: connection ? undefined : draft.apiKey.trim() || undefined, model: draft.model.trim(), resolution: draft.resolution, duration: draft.duration } };
      if (old) updateModel(model.id, model); else addModel(model); back();
    } catch (e) { setError(e instanceof Error ? e.message : String(e)); }
  };
  return <section className={`${cardShell} ${embedded ? '' : 'p-3'} space-y-4`} aria-label={label('视频模型', 'Video models')}>
    <div className="flex items-center justify-between gap-3"><div className="min-w-0"><h3 className="text-sm font-semibold text-stone-800 dark:text-white">{draft ? label(draft.id ? '编辑视频模型' : '添加视频模型', draft.id ? 'Edit video model' : 'Add video model') : label('视频模型', 'Video models')}</h3><p className={`${HUB_HINT} mt-1`}>{label('MiniMax Hailuo · 生成任务可中断后继续。', 'MiniMax Hailuo · Generation tasks can resume.')}</p></div>{draft ? <button className={HUB_SECONDARY} onClick={back}><FiArrowLeft />{label('返回', 'Back')}</button> : <button className={HUB_PRIMARY} aria-label={label('添加视频模型', 'Add video model')} onClick={() => { setDraft({ ...empty }); setError(''); }}><FiPlus />{label('添加', 'Add')}</button>}</div>
    {error && <p role="alert" className={HUB_ERROR}>{error}</p>}
    {draft ? <form className={HUB_FORM} onSubmit={event => { event.preventDefault(); save(); }}>
      <label className={HUB_LABEL}><span>{label('名称', 'Name')}</span><input autoFocus className={HUB_INPUT} value={draft.name} placeholder={draft.model} onChange={e => setDraft({ ...draft, name: e.target.value })} /></label>
      <label className={HUB_LABEL}><span>{label('密钥来源', 'Credential source')}</span><select className={HUB_INPUT} value={draft.connectionId} onChange={e => setDraft({ ...draft, connectionId: e.target.value, apiKey: e.target.value ? '' : draft.apiKey })}><option value="">{label('独立密钥', 'Independent key')}</option>{draft.connectionId && !connections.some(c => c.id === draft.connectionId) && <option value={draft.connectionId}>{label('原服务连接已移除', 'Original service is unavailable')}</option>}{connections.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
      {(!draft.connectionId || !connections.some(c => c.id === draft.connectionId)) && <label className={HUB_LABEL}><span>API Key</span><input className={HUB_INPUT} type="password" autoComplete="off" value={draft.apiKey} onChange={e => setDraft({ ...draft, apiKey: e.target.value })} /></label>}
      <label className={HUB_LABEL}><span>{label('视频服务地址', 'Video endpoint')}</span><input required type="url" className={HUB_INPUT} value={draft.endpoint} onChange={e => setDraft({ ...draft, endpoint: e.target.value })} /></label>
      <label className={HUB_LABEL}><span>{label('模型', 'Model')}</span><input required className={HUB_INPUT} value={draft.model} onChange={e => setDraft({ ...draft, model: e.target.value })} /></label>
      <div className="grid grid-cols-2 gap-3"><label className={HUB_LABEL}><span>{label('分辨率', 'Resolution')}</span><select className={HUB_INPUT} value={draft.resolution} onChange={e => setDraft({ ...draft, resolution: e.target.value as typeof draft.resolution })}>{['480', '720', '768', '1080'].map(v => <option key={v} value={v}>{v}p</option>)}</select></label><label className={HUB_LABEL}><span>{label('时长（秒）', 'Duration (seconds)')}</span><select className={HUB_INPUT} value={draft.duration} onChange={e => setDraft({ ...draft, duration: Number(e.target.value) as 5 | 6 | 10 })}>{[5, 6, 10].map(v => <option key={v} value={v}>{v} {label('秒', 'seconds')}</option>)}</select></label></div>
      <p className={HUB_HINT}>{label('分辨率和时长需符合厂商对该模型的支持范围。', 'Choose a resolution and duration supported by this model.')}</p>
      <div className="flex gap-2 border-t border-stone-200 pt-3 dark:border-slate-700"><button type="submit" className={HUB_PRIMARY}>{label('保存', 'Save')}</button><button type="button" className={HUB_SECONDARY} onClick={back}>{label('取消', 'Cancel')}</button></div>
    </form> : <div className="space-y-2">{!videos.length && <div className={`${HUB_CARD} flex flex-col items-center py-7 text-center`}><FiVideo size={22} className="mb-3 text-stone-400" /><p className="text-xs font-medium text-stone-700 dark:text-slate-200">{label('还没有视频模型', 'No video models yet')}</p><p className={`${HUB_HINT} mt-1`}>{label('添加后，可以直接在对话中要求生成视频。', 'Add one to generate videos directly in chat.')}</p></div>}{videos.map(model => <div key={model.id} className={HUB_CARD}><p className="truncate text-xs font-semibold text-stone-800 dark:text-slate-100">{model.name}</p><p className={`${HUB_HINT} mt-1 truncate`}>{model.videoGeneratorConfig!.model}</p><div className="mt-3 flex flex-wrap gap-1.5"><span className={HUB_BADGE}>{model.videoGeneratorConfig!.resolution ?? '768'}p</span><span className={HUB_BADGE}>{model.videoGeneratorConfig!.duration ?? 6}{label('秒', 's')}</span><span className={HUB_BADGE}>{connections.find(c => c.id === (model.videoGeneratorConfig!.connectionId || (model.videoGeneratorConfig!.apiKey ? '' : model.connectionId)))?.name ?? label('独立密钥', 'Independent key')}</span></div><div className="mt-3 flex gap-2 border-t border-stone-200 pt-3 dark:border-slate-700"><button className={HUB_SECONDARY} onClick={() => { const cfg = model.videoGeneratorConfig!; setError(''); setDraft({ id: model.id, name: model.name, connectionId: cfg.connectionId || (cfg.apiKey ? '' : model.connectionId || ''), apiKey: cfg.apiKey || '', model: cfg.model, endpoint: cfg.endpoint || empty.endpoint, resolution: cfg.resolution || '768', duration: cfg.duration || 6 }); }}><FiEdit2 size={13} />{label('编辑', 'Edit')}</button><button className={`${HUB_SECONDARY} !text-rose-600 dark:!text-rose-300`} onClick={() => void confirmDestructive(label('删除此视频模型配置？', 'Delete this video configuration?')).then(ok => { if (ok) { if (model.isChatModel !== false || model.isImageGenerator) updateModel(model.id, { isVideoGenerator: false, videoGeneratorConfig: undefined }); else removeModel(model.id); } })}><FiTrash2 size={13} />{label('删除', 'Delete')}</button></div></div>)}</div>}
    <p className={HUB_HINT}>{label('应用保存云端任务编号。停止本地等待后，厂商任务可能继续运行。', 'Remote task IDs are saved. Provider jobs may continue after you stop waiting locally.')}</p>
  </section>;
}
