import { useEffect, useState } from 'react';
import { useSettingStore } from '../../store/settingStore';
import { runtimeEnglish } from './runtimeEnglish';
import { flushZustandFilePersist, suspendFilePersistForRestore, resumeFilePersistAfterRestoreFailure } from '../../utils/zustandFileStorage';
import { FiClock, FiLink, FiDatabase, FiPlay, FiSquare, FiRefreshCw, FiTrash2 } from 'react-icons/fi';
import type { RuntimeAPI, RuntimeSnapshot, RuntimeTask, RuntimeSchedule, McpConnection, McpTool, BackupPreview, McpCallResult, TaskKind } from './api';
const inputClass='w-full rounded-lg border border-stone-300 bg-white px-3 py-2 text-sm text-stone-900 focus:border-cyan-500 focus:outline-none dark:border-slate-600 dark:bg-slate-900/40 dark:text-slate-100';
const buttonClass='inline-flex items-center gap-1.5 rounded-lg border border-stone-300 px-3 py-2 text-sm hover:bg-stone-100 disabled:opacity-40 dark:border-slate-600 dark:hover:bg-slate-700';
const statusLabels:Record<string,string>={queued:'等待开始',running:'运行中',awaiting_action:'等待操作',completed:'完成',failed:'失败',cancelled:'已停止',interrupted:'可继续'};
function localDateInput(ms:number):string{const date=new Date(ms);return new Date(ms-date.getTimezoneOffset()*60_000).toISOString().slice(0,16);}

function taskOutputFiles(task:RuntimeTask):Array<{path:string;name:string}>{const result=task.result as {localPath?:unknown;files?:unknown[]}|undefined;if(!result||typeof result!=='object')return[];if(typeof result.localPath==='string')return[{path:result.localPath,name:result.localPath.split(/[\\/]/).at(-1)||'Video'}];return(Array.isArray(result.files)?result.files:[]).flatMap(raw=>{if(!raw||typeof raw!=='object')return[];const file=raw as {path?:unknown;name?:unknown};return typeof file.path==='string'?[{path:file.path,name:typeof file.name==='string'?file.name:file.path.split(/[\\/]/).at(-1)||'File'}]:[];});}
export default function RuntimePanel({api:providedApi}:{api?:RuntimeAPI}) {
  const locale=useSettingStore(state=>state.locale);
  const tr=(text:string)=>locale==='en'?runtimeEnglish[text]||text:text;
  const api=providedApi||window.electron as unknown as RuntimeAPI;
  const [snapshot,setSnapshot]=useState<RuntimeSnapshot>({tasks:[],schedules:[],connections:[]});
  const [tab,setTab]=useState<'tasks'|'connections'|'backup'>('tasks');
  const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);
  const [showSchedule,setShowSchedule]=useState(false);
  const [schedule,setSchedule]=useState({title:'',kind:'reminder' as TaskKind,prompt:'',nextRun:localDateInput(Date.now()+3600_000),interval:'',url:'',directory:''});
  const [connection,setConnection]=useState<McpConnection>({id:'',name:'',transport:'http',url:'',token:'',enabled:false});
  const [showConnection,setShowConnection]=useState(false);const [args,setArgs]=useState('[]');const [env,setEnv]=useState('{}');
  const [toolConnection,setToolConnection]=useState('');const [tools,setTools]=useState<McpTool[]>([]);const [selectedTool,setSelectedTool]=useState('');const [toolArgs,setToolArgs]=useState('{}');const [toolResult,setToolResult]=useState<McpCallResult|null>(null);
  const [snapshots,setSnapshots]=useState<Array<{id:string;createdAt:number;label:string}>>([]);
  const [password,setPassword]=useState('');const [preview,setPreview]=useState<BackupPreview|null>(null);
  const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');setNotice('');try{await fn();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}};
  useEffect(()=>{if(!api?.runtimeGetState)return;void api.runtimeGetState().then(setSnapshot).catch(e=>setError(String(e)));return api.onRuntimeChanged(setSnapshot);},[api]);
  useEffect(()=>{if(tab==='backup'&&api.runtimeListSnapshots)void api.runtimeListSnapshots().then(setSnapshots).catch(e=>setError(String(e)));},[tab,api]);
  const saveSchedule=()=>run(async()=>{const value:Omit<RuntimeSchedule,'id'>={title:schedule.title,kind:schedule.kind,prompt:schedule.prompt,nextRunAt:new Date(schedule.nextRun).getTime(),intervalMinutes:schedule.interval?Number(schedule.interval):undefined,enabled:true,url:schedule.url||undefined,directory:schedule.directory||undefined};await api.runtimeSaveSchedule(value);setShowSchedule(false);setNotice('计划已保存；应用退出期间不执行，错过的计划会等待你处理。');});
  const saveConnection=()=>run(async()=>{const parsedArgs=JSON.parse(args),parsedEnv=JSON.parse(env);if(!Array.isArray(parsedArgs)||parsedArgs.some(v=>typeof v!=='string')||!parsedEnv||Array.isArray(parsedEnv)||typeof parsedEnv!=='object'||Object.values(parsedEnv).some(v=>typeof v!=='string'))throw new Error('参数需要字符串数组，环境变量需要字符串字典');await api.runtimeSaveConnection({...connection,args:parsedArgs,env:parsedEnv});setShowConnection(false);setConnection({id:'',name:'',transport:'http',url:'',token:'',enabled:false});setNotice('连接已保存；点击连接才会启动服务。');});
  const reload=()=>window.location.reload();
  const restoreAndReload=async(previewId:string,mode:'merge'|'replace')=>{await suspendFilePersistForRestore();try{await api.runtimeRestoreBackup({previewId,mode});reload();}catch(error){resumeFilePersistAfterRestoreFailure();throw error;}};
  const rollbackAndReload=async(id:string)=>{await suspendFilePersistForRestore();try{await api.runtimeRollbackBackup(id);reload();}catch(error){resumeFilePersistAfterRestoreFailure();throw error;}};
  return <section className="space-y-5 text-stone-800 dark:text-slate-200" aria-label={tr('任务、服务连接与备份')}>
    <div><h2 className="text-lg font-semibold">{tr('任务与连接')}</h2><p className="mt-1 text-sm text-stone-500 dark:text-slate-400">{tr('持续处理任务、连接外部工具，安全迁移你的全部资料。')}</p></div>
    <div className="flex flex-wrap gap-2">{([['tasks','任务与计划',FiClock],['connections','外部服务',FiLink],['backup','备份与迁移',FiDatabase]] as const).map(([key,label,Icon])=><button key={key} className={`${buttonClass} ${tab===key?'border-cyan-500 text-cyan-700 dark:text-cyan-300':''}`} onClick={()=>setTab(key)}><Icon/>{tr(label)}</button>)}</div>
    {snapshot.recoveryError&&<div role="alert" className="rounded-lg bg-amber-50 p-3 text-sm text-amber-800 dark:bg-amber-950/40 dark:text-amber-200">{snapshot.recoveryError}</div>}
    {error&&<div role="alert" className="rounded-lg bg-red-50 dark:bg-red-950/40 p-3 text-sm text-red-700 dark:text-red-300">{error}</div>}{notice&&<div role="status" className="rounded-lg bg-cyan-50 dark:bg-cyan-950/40 p-3 text-sm text-cyan-800 dark:text-cyan-200">{notice}</div>}
    {tab==='tasks'&&<>
      <div className="flex items-center justify-between"><h3 className="font-medium">{tr('定时与变化监控')}</h3><button className={buttonClass} onClick={()=>setShowSchedule(!showSchedule)}>{tr('添加计划')}</button></div>
      <p className="text-xs text-stone-500 dark:text-slate-400">{tr('应用需保持运行。休眠或退出时错过的任务会标记为“已错过”，不会在启动时静默补发请求。网页按内容摘要监控；目录按文件名、大小与修改时间监控。')}</p>
      {showSchedule&&<div className="space-y-3 rounded-xl border border-stone-200 dark:border-slate-700 p-4">
        <input className={inputClass} aria-label={tr('计划名称')} placeholder={tr('计划名称')} value={schedule.title} onChange={e=>setSchedule({...schedule,title:e.target.value})}/>
        <select className={inputClass} aria-label={tr('计划类型')} value={schedule.kind} onChange={e=>setSchedule({...schedule,kind:e.target.value as TaskKind})}><option value="reminder">{tr('提醒')}</option><option value="agent">{tr('执行助手任务')}</option><option value="web-monitor">{tr('网页变化')}</option><option value="directory-monitor">{tr('目录变化')}</option></select>
        {(schedule.kind==='agent'||schedule.kind==='reminder')&&<textarea className={inputClass} aria-label={tr('任务内容')} rows={3} placeholder={schedule.kind==='agent'?tr('例如：根据上传的资料生成周报 Word 文件'):tr('提醒内容')} value={schedule.prompt} onChange={e=>setSchedule({...schedule,prompt:e.target.value})}/>}
        {schedule.kind==='web-monitor'&&<input className={inputClass} aria-label={tr('网页地址')} placeholder="https://example.com" value={schedule.url} onChange={e=>setSchedule({...schedule,url:e.target.value})}/>}
        {schedule.kind==='directory-monitor'&&<div className="flex items-center gap-2"><button className={buttonClass} disabled={busy} onClick={()=>void run(async()=>{const directory=await api.runtimeChooseDirectory();if(directory)setSchedule({...schedule,directory});})}>{tr('选择目录')}</button><span className="break-all text-xs">{schedule.directory||tr('仅读取你选择目录的文件元信息')}</span></div>}
        <div className="grid gap-3 sm:grid-cols-2"><label className="space-y-1 text-sm">{tr('首次执行')}<input className={inputClass} type="datetime-local" value={schedule.nextRun} onChange={e=>setSchedule({...schedule,nextRun:e.target.value})}/></label><label className="space-y-1 text-sm">{tr('重复间隔（分钟，留空仅一次）')}<input className={inputClass} type="number" min="1" value={schedule.interval} onChange={e=>setSchedule({...schedule,interval:e.target.value})}/></label></div>
        <button className={buttonClass} disabled={busy||!schedule.title.trim()} onClick={()=>void saveSchedule()}>{tr('保存计划')}</button>
      </div>}
      <div className="space-y-2">{snapshot.schedules.map(item=><div key={item.id} className="rounded-xl border border-stone-200 dark:border-slate-700 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><span className="font-medium">{item.title}</span><div className="flex gap-2"><button className={buttonClass} disabled={busy} onClick={()=>void run(async()=>{await api.runtimeRunSchedule(item.id);})}><FiPlay/>{tr('执行一次')}</button><button className={buttonClass} disabled={busy} onClick={()=>void run(async()=>{await api.runtimeSaveSchedule({...item,enabled:!item.enabled,nextRunAt:Math.max(Date.now()+60_000,item.nextRunAt)});})}>{item.enabled?tr('暂停'):tr('启用')}</button><button aria-label={tr('删除计划')} className={buttonClass} disabled={busy} onClick={()=>void run(async()=>{await api.runtimeDeleteSchedule(item.id);})}><FiTrash2/></button></div></div><p className="mt-2 text-xs text-stone-500 dark:text-slate-400">{item.missedAt?tr('已错过 · 请手动处理'):item.enabled?`${locale==='en'?'Next':'下次'}: ${new Date(item.nextRunAt).toLocaleString()}`:tr('已暂停')}{item.lastCheckedAt?` · ${locale==='en'?'Last checked':'最近检查'}: ${new Date(item.lastCheckedAt).toLocaleString()}`:''}</p>{item.lastError&&<p className="mt-2 text-xs text-amber-700 dark:text-amber-300">{item.lastError}</p>}</div>)}</div>
      <h3 className="font-medium">{tr('任务记录')}</h3>{!snapshot.tasks.length&&<p className="text-sm text-stone-500 dark:text-slate-400">{tr('执行的任务和步骤会保存在这里；中断后可继续已保存的进度。')}</p>}
      <div className="space-y-2">{[...snapshot.tasks].reverse().slice(0,100).map(task=><details key={task.id} className="rounded-xl border border-stone-200 dark:border-slate-700 p-3"><summary className="cursor-pointer"><span>{task.title}</span><span className="ml-3 text-xs text-stone-500 dark:text-slate-400">{tr(statusLabels[task.status])} · {new Date(task.updatedAt).toLocaleString()}</span></summary><div className="mt-3 space-y-2">{task.error&&<p className="text-sm text-amber-700 dark:text-amber-300">{task.error}</p>}{task.steps.map(step=><div key={step.key} className="text-sm"><span>{tr(statusLabels[step.status]||step.status)} · {step.title}</span>{step.error&&<p className="text-red-700 dark:text-red-300">{step.error}</p>}</div>)}{taskOutputFiles(task).map(file=><button key={file.path} className={buttonClass} onClick={()=>void window.electron.openLocalFile({path:file.path})}>{tr('打开文件')} · {file.name}</button>)}{task.result!==undefined&&<pre className="max-h-40 overflow-auto whitespace-pre-wrap text-xs text-stone-500 dark:text-slate-400">{typeof task.result==='string'?task.result:JSON.stringify(task.result,null,2)}</pre>}<div className="flex gap-2">{['failed','interrupted','cancelled'].includes(task.status)&&<button className={buttonClass} disabled={busy} onClick={()=>void run(async()=>{await api.runtimeRetryTask(task.id);})}><FiRefreshCw/>{tr('继续')}</button>}{task.status==='queued'&&<button className={buttonClass} disabled={busy} onClick={()=>void run(async()=>{await api.runtimeStartTask(task.id);})}><FiPlay/>{tr('开始')}</button>}{['running','queued','awaiting_action'].includes(task.status)&&<button className={buttonClass} disabled={busy} onClick={()=>void run(async()=>{await api.runtimeCancelTask(task.id);})}><FiSquare/>{tr('停止')}</button>}</div></div></details>)}</div>
    </>}
    {tab==='connections'&&<>
      {(snapshot.pendingMcpCalls||[]).map(call=><div key={call.id} className="space-y-2 rounded-xl border border-amber-400 dark:border-amber-700 p-3"><p className="text-sm text-amber-800 dark:text-amber-200">{locale==='en'?'The assistant requests':'助手请求执行'} {call.tool} ({snapshot.connections.find(c=>c.id===call.connectionId)?.name}). {locale==='en'?'This may modify external data and needs approval.':'此操作可能修改外部数据，需要批准。'}</p><pre className="max-h-32 overflow-auto whitespace-pre-wrap text-xs">{JSON.stringify(call.args,null,2)}</pre><div className="flex gap-2"><button className={buttonClass} disabled={busy} onClick={()=>void run(async()=>{setToolResult(await api.runtimeApproveMcpCall(call.id));})}>{tr('批准本次调用')}</button><button className={buttonClass} disabled={busy} onClick={()=>void run(async()=>{await api.runtimeCancelMcpCall(call.id);})}>{tr('拒绝')}</button></div></div>)}
      <p className="text-sm text-stone-500 dark:text-slate-400">{tr('连接支持 MCP 的本地程序或远程服务。写入、删除或未声明只读的工具，需要你单次批准。凭证保存在系统加密存储中。')}</p>
      <button className={buttonClass} onClick={()=>setShowConnection(!showConnection)}>{tr('添加 MCP 服务')}</button>
      {showConnection&&<div className="space-y-3 rounded-xl border border-stone-200 dark:border-slate-700 p-4"><input className={inputClass} aria-label={tr('服务名称')} placeholder={tr('服务名称')} value={connection.name} onChange={e=>setConnection({...connection,name:e.target.value})}/><select className={inputClass} aria-label={tr('连接方式')} value={connection.transport} onChange={e=>setConnection({...connection,transport:e.target.value as 'http'|'stdio'})}><option value="http">{tr('远程 HTTP（Streamable HTTP）')}</option><option value="stdio">{tr('本地程序（stdio）')}</option></select>
        {connection.transport==='http'?<><input className={inputClass} aria-label={tr('MCP 地址')} placeholder="https://example.com/mcp" value={connection.url||''} onChange={e=>setConnection({...connection,url:e.target.value})}/><input className={inputClass} type="password" aria-label={tr('服务凭证')} placeholder={tr('Bearer Token（可选）')} value={connection.token||''} onChange={e=>setConnection({...connection,token:e.target.value})}/></>:<><input className={inputClass} aria-label={tr('启动程序')} placeholder={tr('程序名称或完整路径，例如 npx')} value={connection.command||''} onChange={e=>setConnection({...connection,command:e.target.value})}/><label className="block space-y-1 text-sm">{tr('启动参数（JSON 数组）')}<textarea className={inputClass} value={args} onChange={e=>setArgs(e.target.value)}/></label><label className="block space-y-1 text-sm">{tr('环境变量（JSON 字典，值加密保存）')}<textarea className={inputClass} value={env} onChange={e=>setEnv(e.target.value)}/></label><p className="text-xs text-amber-700 dark:text-amber-300">{tr('连接时会按上述参数启动本地程序；只添加你信任的程序。')}</p></>}
        <button className={buttonClass} disabled={busy||!connection.name.trim()} onClick={()=>void saveConnection()}>{tr('保存连接')}</button></div>}
      <div className="space-y-2">{snapshot.connections.map(item=><div key={item.id} className="flex flex-wrap items-center justify-between gap-2 rounded-xl border border-stone-200 dark:border-slate-700 p-3"><div><p>{item.name}</p><p className="text-xs text-stone-500 dark:text-slate-400">{item.transport==='http'?item.url:item.command} · {item.status==='connected'?tr('已连接'):tr('未连接')}</p></div><div className="flex gap-2"><button className={buttonClass} disabled={busy} onClick={()=>void run(async()=>{if(item.status==='connected'){await api.runtimeDisconnect(item.id);if(toolConnection===item.id){setTools([]);setToolConnection('');}}else{setTools(await api.runtimeConnect(item.id));setToolConnection(item.id);setSelectedTool('');setToolResult(null);}})}>{item.status==='connected'?tr('断开'):tr('连接')}</button>{item.status==='connected'&&<button className={buttonClass} disabled={busy} onClick={()=>void run(async()=>{setTools(await api.runtimeListTools(item.id));setToolConnection(item.id);setToolResult(null);})}>{tr('工具')}</button>}<button className={buttonClass} onClick={()=>{setConnection(item);setArgs(JSON.stringify(item.args||[]));setEnv(JSON.stringify(item.env||{}));setShowConnection(true);}}>{tr('编辑')}</button><button className={buttonClass} aria-label={tr('移除服务')} disabled={busy} onClick={()=>void run(async()=>{await api.runtimeDeleteConnection(item.id);if(toolConnection===item.id){setTools([]);setToolConnection('');}})}><FiTrash2/></button></div></div>)}</div>
      {toolConnection&&<div className="space-y-3 rounded-xl border border-stone-200 dark:border-slate-700 p-4"><h3 className="font-medium">{locale==='en'?'Service tools':'服务工具'} · {tools.length}</h3><select className={inputClass} aria-label={tr('选择工具')} value={selectedTool} onChange={e=>{setSelectedTool(e.target.value);setToolResult(null);}}><option value="">{tr('选择工具')}</option>{tools.map(tool=><option key={tool.name} value={tool.name}>{tool.name} · {tool.readOnly?tr('只读'):tr('需要批准')}</option>)}</select>{selectedTool&&<><p className="text-sm text-stone-500 dark:text-slate-400">{tools.find(t=>t.name===selectedTool)?.description}</p><details><summary className="text-xs text-stone-500 dark:text-slate-400">{tr('参数格式')}</summary><pre className="max-h-36 overflow-auto whitespace-pre-wrap text-xs">{JSON.stringify(tools.find(t=>t.name===selectedTool)?.inputSchema,null,2)}</pre></details><textarea className={inputClass} aria-label={tr('工具参数')} rows={3} value={toolArgs} onChange={e=>setToolArgs(e.target.value)}/><button className={buttonClass} disabled={busy} onClick={()=>void run(async()=>{const parsed=JSON.parse(toolArgs);if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))throw new Error('工具参数需要 JSON 对象');setToolResult(await api.runtimeCallTool({connectionId:toolConnection,tool:selectedTool,args:parsed}));})}>{tr('运行工具')}</button></>}
        {toolResult?.authorizationRequired&&<div className="space-y-2 rounded-lg border border-amber-400 dark:border-amber-700 p-3"><p className="text-sm text-amber-800 dark:text-amber-200">{tr('此工具可能修改外部数据，请检查后批准本次调用。')}</p><pre className="max-h-40 overflow-auto whitespace-pre-wrap text-xs">{JSON.stringify(toolResult.authorizationRequired.args,null,2)}</pre><div className="flex gap-2"><button className={buttonClass} disabled={busy} onClick={()=>void run(async()=>{setToolResult(await api.runtimeApproveMcpCall(toolResult.authorizationRequired!.id));})}>{tr('批准并执行本次调用')}</button><button className={buttonClass} disabled={busy} onClick={()=>void run(async()=>{await api.runtimeCancelMcpCall(toolResult.authorizationRequired!.id);setToolResult(null);})}>{tr('拒绝')}</button></div></div>}
        {(toolResult?.result!==undefined||toolResult?.error)&&<pre className="max-h-64 overflow-auto whitespace-pre-wrap text-xs">{toolResult.error||JSON.stringify(toolResult.result,null,2)}</pre>}</div>}
    </>}
    {tab==='backup'&&<>
      <p className="text-sm text-stone-500 dark:text-slate-400">{tr('完整备份包括配置、会话、记忆、配方、任务，以及应用管理的上传与生成附件。密钥用备份口令重新加密，支持迁移到另一台电脑。')}</p>
      <p className="text-xs text-stone-500 dark:text-slate-400">{tr('单文件上限 128 MB，总内容上限 512 MB。外部资料目录仅保留引用，恢复后需重新选择。请保存口令，忘记后无法解密。')}</p>
      <input className={inputClass} aria-label={tr('备份口令')} type="password" autoComplete="new-password" placeholder={tr('备份口令（至少 8 位）')} value={password} onChange={e=>setPassword(e.target.value)}/>
      <div className="flex flex-wrap gap-2"><button className={buttonClass} disabled={busy||password.length<8} onClick={()=>void run(async()=>{await flushZustandFilePersist();const result=await api.runtimeExportBackup({password});if(result.path){setNotice(`备份已保存：${result.path} · ${result.files} 个文件`);setPassword('');}})}>{tr('导出完整备份')}</button><button className={buttonClass} disabled={busy||password.length<8} onClick={()=>void run(async()=>{await flushZustandFilePersist();const result=await api.runtimePreviewBackup({password});if(result){setPreview(result);setPassword('');}})}>{tr('选择备份并预检')}</button></div>
      {preview&&<div className="space-y-3 rounded-xl border border-stone-200 dark:border-slate-700 p-4"><h3 className="font-medium">{tr('恢复预览')}</h3><p className="text-sm">{locale==='en'?'Created':'创建于'} {new Date(preview.createdAt).toLocaleString()} · {preview.files} {locale==='en'?'files':'个文件'} · {(preview.bytes/1024/1024).toFixed(1)} MB</p><p className="text-xs text-stone-500 dark:text-slate-400">{preview.repositories.join('、')}</p>{preview.warnings.map((warning,i)=><p key={i} className="text-xs text-amber-700 dark:text-amber-300">{warning}</p>)}<details><summary className="text-sm">{preview.conflicts.length} {locale==='en'?'conflicts (merge keeps local values)':'项冲突（合并时保留本机版本）'}</summary><ul className="max-h-40 overflow-auto text-xs">{preview.conflicts.map((conflict,i)=><li key={i}>{conflict}</li>)}</ul></details><div className="flex flex-wrap gap-2"><button className={buttonClass} disabled={busy} onClick={()=>void run(async()=>{await restoreAndReload(preview.id,'merge');})}>{tr('合并（保留本机冲突项）')}</button><button className={`${buttonClass} border-amber-400 dark:border-amber-700 text-amber-700 dark:text-amber-300`} disabled={busy} onClick={()=>void run(async()=>{await restoreAndReload(preview.id,'replace');})}>{tr('使用备份覆盖对应仓库')}</button><button className={buttonClass} onClick={()=>setPreview(null)}>{tr('取消')}</button></div></div>}
      {snapshots.length>0&&<details><summary className="text-sm">{locale==='en'?'Local restore snapshots':'本机恢复快照'} ({snapshots.length})</summary><div className="mt-2 space-y-2">{snapshots.map(item=><div key={item.id} className="flex items-center justify-between gap-2 rounded-lg border border-stone-200 dark:border-slate-700 p-3"><span className="text-xs">{item.label} · {new Date(item.createdAt).toLocaleString()}</span><button className={buttonClass} disabled={busy} onClick={()=>void run(async()=>{await rollbackAndReload(item.id);})}>{tr('恢复此快照')}</button></div>)}</div></details>}

    </>}
  </section>;
}
