import {describe,it,expect,vi,beforeEach} from 'vitest';
const state=vi.hoisted(()=>({sessions:[] as any[]}));
vi.mock('../../store/chatStore',()=>({useChatStore:{getState:()=>state}}));
import {createSessionTask,finishSessionTask,cancelSessionTask,sessionTask,saveSessionCheckpoint} from './taskBridge';
import type {RuntimeTask} from './api';
import type {Message} from '../../types';
const user:Message={id:'user',role:'user',content:'hello',timestamp:1};
const task=():RuntimeTask=>({id:'task',title:'hello',kind:'agent',status:'queued',steps:[],createdAt:1,updatedAt:1,checkpoint:{userMessageId:'user'}});
beforeEach(()=>{state.sessions=[];vi.restoreAllMocks();});
describe('foreground task bridge',()=>{
 it('does not create project-linked tasks from an old conversation',async()=>{const id='bridge-legacy';state.sessions=[{id,projectId:'old-project',messages:[user]}];const create=vi.spyOn(window.electron,'runtimeCreateTask').mockResolvedValue(task());vi.spyOn(window.electron,'runtimeClaimTask').mockResolvedValue({...task(),status:'running'});vi.spyOn(window.electron,'runtimeCancelTask').mockResolvedValue({...task(),status:'cancelled'});await createSessionTask(id,user);expect(create.mock.calls[0][0]).not.toHaveProperty('projectId');await cancelSessionTask(id);});
 it('claims without dispatch and persists checkpoints before completing',async()=>{const id='bridge-success';state.sessions=[{id,messages:[user,{id:'reply',role:'assistant',content:'done',timestamp:2}]}];const create=vi.spyOn(window.electron,'runtimeCreateTask').mockResolvedValue(task());const claim=vi.spyOn(window.electron,'runtimeClaimTask').mockResolvedValue({...task(),status:'running'});const checkpoint=vi.spyOn(window.electron,'runtimeSaveCheckpoint').mockResolvedValue({...task(),status:'running'});const complete=vi.spyOn(window.electron,'runtimeCompleteTask').mockResolvedValue({...task(),status:'completed'});await createSessionTask(id,user);expect(create).toHaveBeenCalledOnce();expect(claim).toHaveBeenCalledWith('task');await saveSessionCheckpoint(id,{round:3});expect(checkpoint.mock.calls[0][0].checkpoint.round).toBe(3);await finishSessionTask(id);expect(complete.mock.calls[0][0].error).toBeUndefined();expect(sessionTask(id)).toBeUndefined();});
 it('records an empty model response as failed instead of completed',async()=>{const id='bridge-empty';state.sessions=[{id,messages:[user,{id:'reply',role:'assistant',content:'',timestamp:2}]}];vi.spyOn(window.electron,'runtimeCreateTask').mockResolvedValue(task());vi.spyOn(window.electron,'runtimeClaimTask').mockResolvedValue({...task(),status:'running'});const complete=vi.spyOn(window.electron,'runtimeCompleteTask').mockResolvedValue({...task(),status:'failed'});await createSessionTask(id,user);await finishSessionTask(id);expect(complete.mock.calls[0][0].error).toContain('未收到有效回答');});
 it('records a streamed error bubble as failed even when it has readable text',async()=>{const id='bridge-stream-error';state.sessions=[{id,messages:[user,{id:'reply',role:'assistant',content:'请求失败：流式连接断开',meta:{taskError:'连接断开'},timestamp:2}]}];vi.spyOn(window.electron,'runtimeCreateTask').mockResolvedValue(task());vi.spyOn(window.electron,'runtimeClaimTask').mockResolvedValue({...task(),status:'running'});const complete=vi.spyOn(window.electron,'runtimeCompleteTask').mockResolvedValue({...task(),status:'failed'});await createSessionTask(id,user);await finishSessionTask(id);expect(complete.mock.calls[0][0].error).toBe('连接断开');});
 it('cancels a creation in flight without later claiming or completing it',async()=>{const id='bridge-cancel';let resolve!:(value:RuntimeTask)=>void;vi.spyOn(window.electron,'runtimeCreateTask').mockImplementation(()=>new Promise(done=>{resolve=done;}));const claim=vi.spyOn(window.electron,'runtimeClaimTask');const cancel=vi.spyOn(window.electron,'runtimeCancelTask').mockResolvedValue({...task(),status:'cancelled'});const creating=createSessionTask(id,user);const cancelling=cancelSessionTask(id);resolve(task());await Promise.all([creating,cancelling]);expect(cancel).toHaveBeenCalledWith('task');expect(claim).not.toHaveBeenCalled();expect(sessionTask(id)).toBeUndefined();});
});
