import type { ModelConfig } from '../../../src/types';
import { resolveImageProviderId, type InferredImageProviderId } from '../../../src/utils/imageProviderPresets';

export function sanitizeSecretToken(raw: string): string { return String(raw ?? '').replace(/[\u200B-\u200D\uFEFF]/g, '').trim().replace(/^["']+|["']+$/g, '').replace(/\s+/g, ''); }
export function normalizeBearerAuthorization(headerValue: string): string { const t = sanitizeSecretToken(headerValue); if (!t) return t; return /^bearer\s+/i.test(t) ? t : `Bearer ${t}`; }
export function hasExplicitAuthorizationHeader(headers: Record<string, string>): boolean { return Object.keys(headers).some((k) => k.toLowerCase() === 'authorization'); }
export function getAuthorizationHeaderValue(headers: Record<string, string>): string | undefined { for (const [k, v] of Object.entries(headers)) if (k.toLowerCase() === 'authorization') { const t = String(v ?? '').trim(); return t || undefined; } return undefined; }
export function secretKeyHint(authorizationOrRaw: string | undefined): string { if (!authorizationOrRaw) return ''; const k = sanitizeSecretToken(authorizationOrRaw.replace(/^bearer\s+/i, '')); if (!k) return ''; if (k.length <= 4) return '****'; return `…${k.slice(-4)}`; }
export function bearerFromEnvCandidates(env: Record<string, string> | undefined, candidates: string[]): string | undefined { if (!env) return undefined; for (const k of candidates) { const raw = typeof env[k] === 'string' ? sanitizeSecretToken(env[k]) : ''; if (raw) return normalizeBearerAuthorization(raw); } return undefined; }
export function firstMatchingEnvKey(env: Record<string, string> | undefined, candidates: string[]): string | undefined { if (!env) return undefined; for (const k of candidates) { const raw = typeof env[k] === 'string' ? sanitizeSecretToken(env[k]) : ''; if (raw) return k; } return undefined; }
export const VOLC_API_KEY_CANDIDATES = ['ARK_API_KEY', 'VOLC_ENGINE_API_KEY', 'VOLCES_API_KEY', 'VOLC_IMAGE_API_KEY'];
export const BAILIAN_API_KEY_CANDIDATES = ['DASHSCOPE_API_KEY', 'BAILIAN_API_KEY', 'ALIYUN_API_KEY'];
export const OPENAI_API_KEY_CANDIDATES = ['OPENAI_API_KEY', 'REMOTE_API_KEY'];
export const ZHIPU_API_KEY_CANDIDATES = ['ZHIPU_API_KEY', 'BIGMODEL_API_KEY', 'GLM_API_KEY'];
export const MINIMAX_API_KEY_CANDIDATES = ['MINIMAX_API_KEY', 'MINIMAX_TOKEN'];
export function effectiveImageProvider(config: NonNullable<ModelConfig['imageGeneratorConfig']>, endpoint?: string): InferredImageProviderId | undefined { const ep = (endpoint ?? config.endpoint ?? '').trim(); const formatHint = config.httpFormat && config.httpFormat !== 'auto' ? config.httpFormat : undefined; return resolveImageProviderId(config.provider, ep, formatHint); }
export function resolveProviderBearer(config: NonNullable<ModelConfig['imageGeneratorConfig']>, env: Record<string, string> | undefined): string | undefined { const structured = typeof config.apiKey === 'string' ? sanitizeSecretToken(config.apiKey) : ''; if (structured) return normalizeBearerAuthorization(structured); const provider = effectiveImageProvider(config); switch (provider) { case 'bailian-wanx': return bearerFromEnvCandidates(env, BAILIAN_API_KEY_CANDIDATES); case 'volc-seedream': return bearerFromEnvCandidates(env, VOLC_API_KEY_CANDIDATES); case 'openai-images': return bearerFromEnvCandidates(env, OPENAI_API_KEY_CANDIDATES) ?? bearerFromEnvCandidates(env, VOLC_API_KEY_CANDIDATES); case 'zhipu-cogview': return bearerFromEnvCandidates(env, ZHIPU_API_KEY_CANDIDATES); case 'minimax': return bearerFromEnvCandidates(env, MINIMAX_API_KEY_CANDIDATES); case 'ollama': case 'sdwebui': return undefined; default: return bearerFromEnvCandidates(env, OPENAI_API_KEY_CANDIDATES) ?? bearerFromEnvCandidates(env, BAILIAN_API_KEY_CANDIDATES) ?? bearerFromEnvCandidates(env, MINIMAX_API_KEY_CANDIDATES) ?? bearerFromEnvCandidates(env, ZHIPU_API_KEY_CANDIDATES) ?? bearerFromEnvCandidates(env, VOLC_API_KEY_CANDIDATES); } }
export function mergedCustomHeadersForImageHttp(env: Record<string, string> | undefined, config?: NonNullable<ModelConfig['imageGeneratorConfig']>): Record<string, string> { const merged = extraHttpHeadersFromImageEnv(env); const fromProvider = config ? resolveProviderBearer(config, env) : bearerFromEnvCandidates(env, VOLC_API_KEY_CANDIDATES); if (fromProvider) merged.Authorization = fromProvider; return merged; }
export function headerNameFromEnvSuffix(suffixRaw: string): string { const suffix = suffixRaw.replace(/[^\w_-]/g, ''); const parts = suffix.split(/[_-]+/).filter(Boolean); if (!parts.length) return suffixRaw.trim(); return parts.map((p) => p.charAt(0).toUpperCase() + p.slice(1).toLowerCase()).join('-'); }
export function extraHttpHeadersFromImageEnv(env: Record<string, string> | undefined): Record<string, string> { const extra: Record<string, string> = {}; if (!env) return extra; for (const [k0, val] of Object.entries(env)) { const trimmedKey = k0.trim(); if (!/^HEADER_/i.test(trimmedKey)) continue; const suffix = trimmedKey.slice('HEADER_'.length).trim(); if (!suffix) continue; const name = headerNameFromEnvSuffix(suffix); if (!name) continue; const v = String(val ?? '').trim(); if (v) extra[name] = name.toLowerCase() === 'authorization' ? normalizeBearerAuthorization(v) : v; } return extra; }
