// @vitest-environment node
import { describe,it,expect } from 'vitest';
import fs from 'node:fs/promises';
import path from 'node:path';
import { tmpdir } from 'node:os';
import { zipSync } from 'fflate';
import { revealPortableRuntimeSecrets,protectPortableRuntimeSecrets } from './runtimeSecrets';
import {emptyState} from './taskStore';
import { BackupService,packEncrypted,unpackEncrypted,unpackBoundedZip,safeArchivePath,mergePreservingCurrent } from './backup';
const password='correct-horse-123';
const bytes=(s:string)=>Buffer.from(s);
describe('encrypted backups',()=>{
  it('encrypts secrets, rejects wrong password and tampering',()=>{const archive=packEncrypted({'persist/a.json':bytes('{"apiKey":"secret-one"}')},password);expect(archive.includes(bytes('secret-one'))).toBe(false);expect(Buffer.from(unpackEncrypted(archive,password)['persist/a.json']).toString()).toContain('secret-one');expect(()=>unpackEncrypted(archive,'incorrect-password')).toThrow('口令');archive[archive.length-1]^=1;expect(()=>unpackEncrypted(archive,password)).toThrow('损坏');});
  it('rejects unsafe paths both on export and import',()=>{for(const name of ['../a','/tmp/a','a/../../b','a\\b','C:/a','a/./b','a/file:stream','a/.. /outside','a/CON.txt','a/newline\nname'])expect(safeArchivePath(name)).toBe(false);expect(()=>packEncrypted({'../escape':bytes('bad')},password)).toThrow();expect(()=>unpackBoundedZip(zipSync({'../escape':bytes('bad')}))).toThrow('路径');});
  it('merges new IDs while preserving local conflicting records',()=>{const conflicts:string[]=[];expect(mergePreservingCurrent({state:{items:[{id:'a',name:'local'}]}},{state:{items:[{id:'a',name:'incoming'},{id:'b',name:'new'}]}},'repo',conflicts)).toEqual({state:{items:[{id:'a',name:'local'},{id:'b',name:'new'}]}});expect(conflicts).toEqual(['repo.state.items[a]']);});
  it('migrates attachment paths, prevents stale preview restore, and supports rollback',async()=>{const dir=await fs.mkdtemp(path.join(tmpdir(),'myagent-backup-'));try{const source=path.join(dir,'source'),target=path.join(dir,'target');await fs.mkdir(path.join(source,'persist'),{recursive:true});await fs.mkdir(path.join(source,'uploads'),{recursive:true});await fs.mkdir(path.join(target,'persist'),{recursive:true});const original=path.join(source,'uploads','a.txt');await fs.writeFile(original,'hello');await fs.writeFile(path.join(source,'persist','chat-storage.json'),JSON.stringify({state:{messages:[{id:'m',path:original}]}}));const identity=(x:unknown)=>x;const make=(root:string)=>new BackupService({userData:root,managedRoots:{uploads:path.join(root,'uploads')},reveal:identity,protect:identity,revealRuntime:identity,protectRuntime:identity});const bundle=await make(source).export(password);const service=make(target);const preview=await service.preview(bundle.bytes,password);await fs.writeFile(path.join(target,'persist','new.json'),'{}');await expect(service.restore(preview.id,'merge')).rejects.toThrow('已变化');const second=await service.preview(bundle.bytes,password);const restored=await service.restore(second.id,'merge');expect(JSON.parse(await fs.readFile(path.join(target,'persist','chat-storage.json'),'utf8')).state.messages[0].path).toBe(path.join(target,'uploads','a.txt'));expect(await fs.readFile(path.join(target,'uploads','a.txt'),'utf8')).toBe('hello');await service.rollback(restored.rollbackId);await expect(fs.stat(path.join(target,'uploads','a.txt'))).rejects.toMatchObject({code:'ENOENT'});await expect(fs.readFile(path.join(target,'persist','chat-storage.json'))).rejects.toMatchObject({code:'ENOENT'});expect(await fs.readFile(path.join(target,'persist','new.json'),'utf8')).toBe('{}');}finally{await fs.rm(dir,{recursive:true,force:true});}});
  it('restores document version metadata and reseals provider polling keys for a new machine',async()=>{const dir=await fs.mkdtemp(path.join(tmpdir(),'myagent-portable-'));try{const source=path.join(dir,'source'),target=path.join(dir,'target');await fs.mkdir(path.join(source,'runtime'),{recursive:true});await fs.mkdir(path.join(source,'document-workbench','doc'),{recursive:true});await fs.mkdir(path.join(target,'persist'),{recursive:true});const original=path.join(source,'document-workbench','doc','version.md');await fs.writeFile(original,'# Report');await fs.writeFile(path.join(source,'document-workbench','versions.json'),JSON.stringify([{id:'doc',sourcePath:original,versions:[{id:'v',file:{path:original}}]}]));const state=emptyState();state.tasks.push({id:'video',title:'Video',kind:'video-generation',status:'running',steps:[],checkpoint:{remoteJobId:'job-1',sealedApiKey:'old-machine'},createdAt:1,updatedAt:1});await fs.writeFile(path.join(source,'runtime','state.json'),JSON.stringify(state));const identity=(value:unknown)=>value;const sourceBackup=new BackupService({userData:source,managedRoots:{documentVersions:path.join(source,'document-workbench')},reveal:identity,protect:identity,revealRuntime:value=>revealPortableRuntimeSecrets(value as ReturnType<typeof emptyState>,()=> 'key-for-provider'),protectRuntime:identity});const bundle=await sourceBackup.export(password);expect(bundle.bytes.includes(Buffer.from('key-for-provider'))).toBe(false);const targetBackup=new BackupService({userData:target,managedRoots:{documentVersions:path.join(target,'document-workbench')},reveal:identity,protect:identity,revealRuntime:identity,protectRuntime:value=>protectPortableRuntimeSecrets(value as ReturnType<typeof emptyState>,key=>`new-machine-${key.length}`)});const preview=await targetBackup.preview(bundle.bytes,password);await targetBackup.restore(preview.id,'replace');const tasks=JSON.parse(await fs.readFile(path.join(target,'runtime','state.json'),'utf8')).tasks;expect(tasks[0].status).toBe('interrupted');expect(tasks[0].checkpoint).toEqual({remoteJobId:'job-1',sealedApiKey:'new-machine-16'});const versions=JSON.parse(await fs.readFile(path.join(target,'document-workbench','versions.json'),'utf8'));expect(versions[0].sourcePath).toBe(path.join(target,'document-workbench','doc','version.md'));expect(versions[0].versions[0].file.path).toBe(versions[0].sourcePath);}finally{await fs.rm(dir,{recursive:true,force:true});}});
  it('stops export if a source credential cannot be decrypted',async()=>{const dir=await fs.mkdtemp(path.join(tmpdir(),'myagent-backup-'));try{await fs.mkdir(path.join(dir,'persist'));await fs.writeFile(path.join(dir,'persist','model-storage.json'),'{"apiKey":"enc:v1:bad"}');const identity=(x:unknown)=>x;const service=new BackupService({userData:dir,managedRoots:{},reveal:identity,protect:identity,revealRuntime:identity,protectRuntime:identity});await expect(service.export(password)).rejects.toThrow('无法');}finally{await fs.rm(dir,{recursive:true,force:true});}});
});
