// @vitest-environment node
import {describe,it,expect,vi} from 'vitest';
import fs from 'node:fs/promises';
import path from 'node:path';
import {tmpdir} from 'node:os';
import {TaskLedger} from './taskStore';
import {RuntimeScheduler,directoryFingerprint} from './scheduler';
describe('schedule execution',()=>{
  it('dispatches an old project schedule as ordinary work without importing its project scope',async()=>{const dir=await fs.mkdtemp(path.join(tmpdir(),'myagent-schedule-'));try{const ledger=new TaskLedger(path.join(dir,'state.json'));await ledger.load();const now=Date.now();const scheduled=await ledger.schedule({title:'legacy',kind:'agent',prompt:'report',enabled:true,nextRunAt:now-100});scheduled.projectId='deleted-project';await ledger.save();const dispatch=vi.fn();const scheduler=new RuntimeScheduler(ledger,dispatch,()=>{},()=>{});await scheduler.tick(now);expect(dispatch).toHaveBeenCalledOnce();expect(ledger.state.tasks[0]).not.toHaveProperty('projectId');expect(ledger.state.schedules[0].projectId).toBe('deleted-project');await scheduler.stop();}finally{await fs.rm(dir,{recursive:true,force:true});}});
  it('marks missed wake events instead of dispatching and deduplicates due tasks',async()=>{const dir=await fs.mkdtemp(path.join(tmpdir(),'myagent-schedule-'));try{const ledger=new TaskLedger(path.join(dir,'state.json'));await ledger.load();const now=Date.now();await ledger.schedule({title:'missed',kind:'agent',prompt:'report',enabled:true,nextRunAt:now-120_000});await ledger.schedule({title:'current',kind:'reminder',prompt:'hello',enabled:true,nextRunAt:now-100});const dispatch=vi.fn(),notify=vi.fn();const scheduler=new RuntimeScheduler(ledger,dispatch,notify,()=>{});await scheduler.tick(now);expect(dispatch).not.toHaveBeenCalled();expect(ledger.state.schedules[0].missedAt).toBeDefined();expect(ledger.state.tasks).toHaveLength(1);expect(ledger.state.tasks[0].status).toBe('completed');await scheduler.tick(now);expect(ledger.state.tasks).toHaveLength(1);await scheduler.stop();}finally{await fs.rm(dir,{recursive:true,force:true});}});
  it('directory fingerprint ignores symlinks and detects added/changed files',async()=>{const dir=await fs.mkdtemp(path.join(tmpdir(),'myagent-monitor-'));try{const baseline=await directoryFingerprint(dir);await fs.writeFile(path.join(dir,'a.txt'),'one');const changed=await directoryFingerprint(dir);expect(changed).not.toBe(baseline);await fs.symlink('/etc',path.join(dir,'outside'));expect(await directoryFingerprint(dir)).toBe(changed);await expect(directoryFingerprint(dir,0)).rejects.toThrow('5000');}finally{await fs.rm(dir,{recursive:true,force:true});}});
});
