import {describe,it,expect,vi,beforeEach} from 'vitest';
const mocks=vi.hoisted(()=>({state:{sessions:[] as any[],currentSessionId:null as string|null,loadingSessionIds:new Set<string>(),compressingSessionIds:new Set<string>(),createSession:vi.fn(),switchSession:vi.fn(),isLoadingSession:vi.fn(),isCompressingSession:vi.fn(),clearLoadingForSession:vi.fn()},commit:vi.fn(),listeners:new Set<()=>void>()}));
vi.mock('../../store/chatStore',()=>({useChatStore:{getState:()=>mocks.state,subscribe:(callback:()=>void)=>{mocks.listeners.add(callback);return()=>mocks.listeners.delete(callback);}}}));
vi.mock('../../store/modelStore',()=>({useModelStore:{getState:()=>({getActiveModel:()=>({id:'model',name:'Model'}),models:[],routingRules:[]})}}));
vi.mock('../../store/settingStore',()=>({useSettingStore:{getState:()=>({locale:'zh'})}}));
vi.mock('../../store/webSearchStore',()=>({useWebSearchStore:{getState:()=>({enabled:false})}}));
vi.mock('../../utils/chatModelPolicy',()=>({effectiveWebEnabled:()=>false}));
vi.mock('../../agent/resolveSendModel',()=>({resolveSendModel:()=>({id:'model',name:'Model'})}));
vi.mock('../../utils/branchTree',()=>({getActiveMessages:(messages:unknown[])=>messages}));
vi.mock('../../chat/sendPipeline',()=>({tryClaimSessionSend:(id:string)=>{if(mocks.state.loadingSessionIds.size)return false;mocks.state.loadingSessionIds.add(id);return true;},commitUserMessageAndReply:(options:unknown)=>mocks.commit(options)}));
vi.mock('../personal/runtimeDispatcher',()=>({waitForSessionTaskEnd:async()=>{}}));
import{installQuickChatBridge}from'./quickBridge';
let submit:(request:{id:string;text:string})=>void,cancel:(id:string)=>void;
beforeEach(()=>{mocks.state.sessions=[{id:'primary',messages:[]}];mocks.state.currentSessionId='primary';mocks.state.loadingSessionIds.clear();mocks.state.compressingSessionIds.clear();mocks.commit.mockReset();mocks.state.createSession.mockReset().mockImplementation(()=>{mocks.state.sessions.push({id:'quick',messages:[]});mocks.state.currentSessionId='quick';return'quick';});mocks.state.switchSession.mockReset().mockImplementation(id=>{mocks.state.currentSessionId=id;});mocks.state.isLoadingSession.mockImplementation(id=>mocks.state.loadingSessionIds.has(id));mocks.state.isCompressingSession.mockReturnValue(false);mocks.state.clearLoadingForSession.mockImplementation(id=>mocks.state.loadingSessionIds.delete(id));vi.spyOn(window.electron,'onQuickSubmit').mockImplementation(callback=>{submit=callback;return()=>{};});vi.spyOn(window.electron,'onQuickCancel').mockImplementation(callback=>{cancel=callback;return()=>{};});vi.spyOn(window.electron,'onQuickOpenSession').mockImplementation(()=>()=>{});});
async function flush(){for(let i=0;i<30;i++)await Promise.resolve();}
describe('quick panel conversation bridge',()=>{
 it('rejects a globally busy chat before creating a blank session',async()=>{mocks.state.loadingSessionIds.add('primary');const update=vi.spyOn(window.electron,'quickReplyUpdate').mockResolvedValue();const off=installQuickChatBridge({runModelReply:vi.fn(),stopSession:vi.fn()});submit({id:'request',text:'hello'});await flush();expect(mocks.state.createSession).not.toHaveBeenCalled();expect(mocks.commit).not.toHaveBeenCalled();expect(update).toHaveBeenCalledWith(expect.objectContaining({status:'failed',error:expect.stringContaining('其他对话')}));off();});
 it('uses the ordinary pipeline, preserves the selected conversation, and previews a final reply',async()=>{const update=vi.spyOn(window.electron,'quickReplyUpdate').mockResolvedValue();mocks.commit.mockImplementation(async({sessionId})=>{mocks.state.sessions.find(s=>s.id===sessionId).messages.push({id:'a',role:'assistant',content:'done',timestamp:Date.now()});mocks.state.loadingSessionIds.delete(sessionId);});const off=installQuickChatBridge({runModelReply:vi.fn(),stopSession:vi.fn()});submit({id:'request',text:'hello'});await flush();expect(mocks.commit).toHaveBeenCalledWith(expect.objectContaining({sessionId:'quick',textContent:'hello'}));expect(mocks.state.currentSessionId).toBe('primary');expect(update).toHaveBeenLastCalledWith(expect.objectContaining({status:'completed',content:'done',sessionId:'quick'}));off();});
 it('keeps cancelled status when a late completion arrives',async()=>{let resolve!:()=>void;const update=vi.spyOn(window.electron,'quickReplyUpdate').mockResolvedValue();mocks.commit.mockImplementation(()=>new Promise<void>(done=>{resolve=done;}));const off=installQuickChatBridge({runModelReply:vi.fn(),stopSession:id=>{mocks.state.loadingSessionIds.delete(id);}});submit({id:'request',text:'hello'});await flush();cancel('request');resolve();await flush();expect(update).toHaveBeenLastCalledWith(expect.objectContaining({status:'cancelled'}));off();});
});
