import { FiMic, FiVolume2, FiZap } from 'react-icons/fi';
import { useSettingStore } from '../../store/settingStore';
import { useI18n } from '../../hooks/useI18n';
import { IosSwitch } from '../../components/IosSwitch';
import { HUB_INPUT, HUB_SECONDARY, HUB_CARD, HUB_LABEL, HUB_HINT } from '../modelHub/styles';
export function VoiceQuickSettings({ systemTtsAvailable = null, microphoneMissing = false }: { systemTtsAvailable?: boolean | null; microphoneMissing?: boolean }) {
  const { t, locale } = useI18n(); const label = (zh: string, en: string) => locale === 'en' ? en : zh;
  const { streamResponses, setStreamResponses, speechInputEnabled, setSpeechInputEnabled, voiceWakeEnabled, setVoiceWakeEnabled, voiceWakePhrase, setVoiceWakePhrase, voiceReplyEnabled, setVoiceReplyEnabled, voiceReplyMode, setVoiceReplyMode, volcAsrAppKey, setVolcAsrAppKey, volcAsrAccessKey, setVolcAsrAccessKey, volcAsrResourceId, setVolcAsrResourceId } = useSettingStore();
  const ttsReady = systemTtsAvailable === true;
  return <div className="space-y-4">
    <div><h3 className="text-sm font-semibold text-stone-800 dark:text-white">{label('语音与回答', 'Voice & replies')}</h3><p className={`${HUB_HINT} mt-1`}>{label('输入、回答呈现与快捷对话，集中在这里调整。', 'Control voice input, reply presentation and quick chat here.')}</p></div>
    <section className={`${HUB_CARD} space-y-3`} aria-label={label('回答呈现', 'Reply presentation')}><h4 className="flex items-center gap-2 text-xs font-semibold text-stone-800 dark:text-slate-100"><FiZap />{label('回答呈现', 'Reply presentation')}</h4><div className="flex items-center justify-between gap-3"><span className="text-xs text-stone-700 dark:text-slate-300">{t('settings.stream')}</span><IosSwitch checked={streamResponses} onChange={setStreamResponses} aria-label={t('settings.stream')} /></div><p className={HUB_HINT}>{t('settings.streamDesc')}</p></section>
    <section className={`${HUB_CARD} space-y-3`} aria-label={label('语音输入', 'Voice input')}><h4 className="flex items-center gap-2 text-xs font-semibold text-stone-800 dark:text-slate-100"><FiMic />{label('语音输入', 'Voice input')}</h4><div className="flex items-center justify-between gap-3"><span className="text-xs text-stone-700 dark:text-slate-300">{t('settings.speech.enableMicUi')}</span><IosSwitch checked={!microphoneMissing && speechInputEnabled} disabled={microphoneMissing} onChange={setSpeechInputEnabled} aria-label={t('settings.speech.enableMicUi')} /></div>{microphoneMissing && <p className="text-xs leading-5 text-amber-700 dark:text-amber-300">{t('settings.speech.noMicrophone')}</p>}
      {speechInputEnabled && !microphoneMissing && <><div className="flex items-center justify-between gap-3"><span className="text-xs text-stone-700 dark:text-slate-300">{t('settings.speech.enableWake')}</span><IosSwitch checked={voiceWakeEnabled} onChange={setVoiceWakeEnabled} aria-label={t('settings.speech.enableWake')} /></div>{voiceWakeEnabled && <label className={HUB_LABEL}><span>{t('settings.speech.wakePhrase')}</span><input aria-label={t('settings.speech.wakePhrase')} className={HUB_INPUT} autoComplete="off" value={voiceWakePhrase} onChange={e => setVoiceWakePhrase(e.target.value)} onBlur={e => setVoiceWakePhrase(e.target.value.trim())} placeholder={t('settings.speech.wakePhrasePh')} /><span className={`block ${HUB_HINT}`}>{t('settings.speech.wakeDesc', { phrase: voiceWakePhrase.trim() || t('settings.speech.wakePhrasePh') })}</span></label>}
        <details className="border-t border-stone-200 pt-3 dark:border-slate-700"><summary className="cursor-pointer text-xs font-medium text-stone-700 dark:text-slate-300">{label('火山语音识别服务', 'Volcengine speech service')}</summary><div className="mt-3 space-y-3" data-section="volc-asr-keys"><p className={HUB_HINT}>{t('settings.streamingAsr.volcOnly')} <a className="text-primary-600 underline dark:text-primary-300" href={`https://www.volcengine.com/docs/6561/1354869?lang=${locale === 'en' ? 'en' : 'zh'}`} target="_blank" rel="noopener noreferrer">{t('settings.streamingAsr.docVolcExample')}</a></p><label className={HUB_LABEL}><span>{t('settings.streamingAsr.fieldAppKey')}</span><input type="password" autoComplete="off" className={HUB_INPUT} value={volcAsrAppKey} onChange={e => setVolcAsrAppKey(e.target.value)} /></label><label className={HUB_LABEL}><span>{t('settings.streamingAsr.fieldAccess')}</span><input type="password" autoComplete="off" className={HUB_INPUT} value={volcAsrAccessKey} onChange={e => setVolcAsrAccessKey(e.target.value)} /></label><label className={HUB_LABEL}><span>{t('settings.streamingAsr.fieldResource')}</span><input autoComplete="off" className={HUB_INPUT} value={volcAsrResourceId} onChange={e => setVolcAsrResourceId(e.target.value)} /></label></div></details>
      </>}
    </section>
    <section className={`${HUB_CARD} space-y-3`} aria-label={label('语音回答', 'Spoken replies')}><h4 className="flex items-center gap-2 text-xs font-semibold text-stone-800 dark:text-slate-100"><FiVolume2 />{label('语音回答', 'Spoken replies')}</h4><div className="flex items-center justify-between gap-3"><span className="text-xs text-stone-700 dark:text-slate-300">{t('settings.speech.voiceReply')}</span><IosSwitch checked={ttsReady && voiceReplyEnabled} disabled={!ttsReady} onChange={setVoiceReplyEnabled} aria-label={t('settings.speech.voiceReply')} /></div>{systemTtsAvailable === false ? <p className="text-xs leading-5 text-amber-700 dark:text-amber-300">{t('settings.speech.noSystemTts')}</p> : systemTtsAvailable === null ? <p role="status" className={HUB_HINT}>{label('正在检查系统朗读能力…', 'Checking system speech playback…')}</p> : <p className={HUB_HINT}>{t('settings.speech.voiceReplyDesc')}</p>}<label className={HUB_LABEL}><span>{label('语音回答长度', 'Spoken answer length')}</span><select className={HUB_INPUT} value={voiceReplyMode} onChange={e => setVoiceReplyMode(e.target.value as 'auto' | 'full' | 'summary')}><option value="auto">{label('自动 · 长回答简要朗读', 'Automatic · shorten long replies')}</option><option value="summary">{label('简要朗读', 'Short extracts')}</option><option value="full">{label('完整朗读', 'Full reply')}</option></select></label></section>
    <section className={`${HUB_CARD} space-y-3`} aria-label={label('快捷对话', 'Quick chat')}><h4 className="text-xs font-semibold text-stone-800 dark:text-slate-100">{label('快捷对话', 'Quick chat')}</h4><div className="flex items-center justify-between gap-3"><kbd className="rounded-lg border border-stone-300 bg-white px-2 py-1.5 text-xs text-stone-600 dark:border-slate-600 dark:bg-slate-900 dark:text-slate-300">⌘ / Ctrl + Shift + Space</kbd><button type="button" className={HUB_SECONDARY} onClick={() => void window.electron.showQuickPanel()}>{label('打开', 'Open')}</button></div><p className={HUB_HINT}>{label('朗读时可随时打断，再继续听写。', 'Interrupt spoken replies and continue dictating.')}</p></section>
  </div>;
}
